** Basic Commands

y       	Copy the selected text to clipboard
p       	Paste clipboard contents
dd       	Cut current line
yy       	Copy current line
y$       	Copy to end of line
D       	Cut to end of line
vEU         Switch word to uppercase
:browse e 	Graphical file explorer
!!pwd 	    Execute the pwd unix command and insert output in file
:tabnew 	Creates a new tab
gt          Show next tab
m {a-z} 	Marks current position as {a-z}
' {a-z} 	Move to position {a-z}
'' 	        Move to previous position
z=          For the word under/after the cursor, suggest correctly spelled words.

** Resizing Panes

| C-w = | Resize Windows to Equal Dimentions |


** Searching

*** Ag silver surfer awk grep

location-list::
    Locations for a single window/buffer/file?
    Can have n location-lists open at a time

quickfix window::
    Locations for mutiple windows/bufers/files?
    Can only have one quickfix window open at a time

how is a projects root directory determined?
what is the current working directory?

**** Commands

| cmd | description                                               |
|-----+-----------------------------------------------------------|
| e   | open file and close the quickfix window.                  |
| o   | open file (same as enter).                                |
| go  | preview file (open but maintain focus on ag.vim results). |
| t   | open in a new tab.                                        |
| T   | open in new tab silently.                                 |
| h   | open in horizontal split.                                 |
| H   | open in horizontal split silently.                        |
| v   | open in vertical split.                                   |
| gv  | open in vertical split silently.                          |
| q   | close the quickfix window.                                |
|-----+-----------------------------------------------------------|

